/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author JillWithJ
 */
public class Kontoinstallningar extends javax.swing.JFrame {

    private String anstalldID;
    private InfDB idb;
    private Konto konto;
    
    public Kontoinstallningar(InfDB idb, String anstalldID) {
        
        this.anstalldID = anstalldID;
        this.idb = idb;
        konto = new Konto(anstalldID, idb);
        
        
        
        
        initComponents();
        setSynlighet("alla", false);
        setStatiskaTF(false);
        tfEpost.setText(konto.getEpost());
        tfLosenord.setText(konto.getLosenord());
        tfAdress.setText(konto.getAdress());
        tfTelefonNummer.setText(konto.getTelefonNummer());
        
        
        
    }
    
    
    public void setSynlighet(String vilkenTyp, boolean synlighet){
        
        if(vilkenTyp == "epost"){
            lblNyEpost.setVisible(synlighet);
            tfNyEpost.setVisible(synlighet);
            lblAtNyEpost.setVisible(synlighet);
            btnNyEpost.setVisible(synlighet);
            btnNyEpostAvbryt.setVisible(synlighet);
        }
        if(vilkenTyp == "losenord"){
            lblNyttLosenord.setVisible(synlighet);
            tfNyttLosenord.setVisible(synlighet);
            btnNyttLosenord.setVisible(synlighet);
            btnNyttLosenordAvbryt.setVisible(synlighet);
        }
        if(vilkenTyp == "telefonNummer"){   
            lblNyttTelefonNummer.setVisible(synlighet);
            tfNyttTelefonNummer.setVisible(synlighet);
            btnNyttTelefonNummer.setVisible(synlighet);
            btnNyttTelefonNummerAvbryt.setVisible(synlighet);
        }
        if(vilkenTyp == "adress"){
            lblNyAdress.setVisible(synlighet);
            lblNyAdressNr.setVisible(synlighet);
            lblNyAdressGata.setVisible(synlighet);
            lblNyAdressStad.setVisible(synlighet);
            tfNyAdressNr.setVisible(synlighet);
            tfNyAdressGata.setVisible(synlighet);
            tfNyAdressStad.setVisible(synlighet);
            btnNyAdress.setVisible(synlighet);
            btnNyAdressAvbryt.setVisible(synlighet);
        }
        if(vilkenTyp == "alla"){
            lblNyEpost.setVisible(synlighet);
            tfNyEpost.setVisible(synlighet);
            lblAtNyEpost.setVisible(synlighet);
            btnNyEpost.setVisible(synlighet);
            btnNyEpostAvbryt.setVisible(synlighet);
        
            lblNyttLosenord.setVisible(synlighet);
            tfNyttLosenord.setVisible(synlighet);
            btnNyttLosenord.setVisible(synlighet);
            btnNyttLosenordAvbryt.setVisible(synlighet);
        
            lblNyttTelefonNummer.setVisible(synlighet);
            tfNyttTelefonNummer.setVisible(synlighet);
            btnNyttTelefonNummer.setVisible(synlighet);
            btnNyttTelefonNummerAvbryt.setVisible(synlighet);
            
            lblNyAdress.setVisible(synlighet);
            lblNyAdressNr.setVisible(synlighet);
            lblNyAdressGata.setVisible(synlighet);
            lblNyAdressStad.setVisible(synlighet);
            tfNyAdressNr.setVisible(synlighet);
            tfNyAdressGata.setVisible(synlighet);
            tfNyAdressStad.setVisible(synlighet);
            btnNyAdress.setVisible(synlighet);
            btnNyAdressAvbryt.setVisible(synlighet);
            
            lblFelmeddelande.setVisible(synlighet);
        }
        if(vilkenTyp == "felmeddelande"){
            lblFelmeddelande.setVisible(synlighet);
        }
        
    }
    
    public void setStatiskaTF(boolean inteStatiska){
        
        tfEpost.setEditable(inteStatiska);
        tfLosenord.setEditable(inteStatiska);
        tfTelefonNummer.setEditable(inteStatiska);
        tfAdress.setEditable(inteStatiska);
    }
    
    
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        tfNyEpost = new javax.swing.JTextField();
        btnNyEpost = new javax.swing.JButton();
        lblNyEpost = new javax.swing.JLabel();
        tfEpost = new javax.swing.JTextField();
        lblLosenord = new javax.swing.JLabel();
        tfLosenord = new javax.swing.JTextField();
        tfNyttLosenord = new javax.swing.JTextField();
        lblNyttLosenord = new javax.swing.JLabel();
        btnNyttLosenord = new javax.swing.JButton();
        lblTelefonNummer = new javax.swing.JLabel();
        tfTelefonNummer = new javax.swing.JTextField();
        lblNyttTelefonNummer = new javax.swing.JLabel();
        tfNyttTelefonNummer = new javax.swing.JTextField();
        btnNyttTelefonNummer = new javax.swing.JButton();
        lblAdress = new javax.swing.JLabel();
        tfAdress = new javax.swing.JTextField();
        tfNyAdressNr = new javax.swing.JTextField();
        lblNyAdress = new javax.swing.JLabel();
        btnNyAdress = new javax.swing.JButton();
        btnEpost = new javax.swing.JButton();
        btnLosenord = new javax.swing.JButton();
        btnTelefonNummer = new javax.swing.JButton();
        btnAdress = new javax.swing.JButton();
        lblAtEpost = new javax.swing.JLabel();
        lblAtNyEpost = new javax.swing.JLabel();
        lblFelmeddelande = new javax.swing.JLabel();
        lblNyAdressNr = new javax.swing.JLabel();
        lblNyAdressGata = new javax.swing.JLabel();
        lblNyAdressStad = new javax.swing.JLabel();
        tfNyAdressGata = new javax.swing.JTextField();
        tfNyAdressStad = new javax.swing.JTextField();
        btnNyAdressAvbryt = new javax.swing.JButton();
        btnNyttTelefonNummerAvbryt = new javax.swing.JButton();
        btnNyttLosenordAvbryt = new javax.swing.JButton();
        btnNyEpostAvbryt = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRubrik.setText("Kontoinställningar");

        lblEpost.setText("Epost");

        btnNyEpost.setText("Ändra");
        btnNyEpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyEpostActionPerformed(evt);
            }
        });

        lblNyEpost.setText("Ny Epost ");

        lblLosenord.setText("Lösenord");

        lblNyttLosenord.setText("Nytt Lösenord");

        btnNyttLosenord.setText("Ändra");
        btnNyttLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyttLosenordActionPerformed(evt);
            }
        });

        lblTelefonNummer.setText("Telefonnummer");

        lblNyttTelefonNummer.setText("Nytt Telefonnummer");

        btnNyttTelefonNummer.setText("Ändra");
        btnNyttTelefonNummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyttTelefonNummerActionPerformed(evt);
            }
        });

        lblAdress.setText("Adress");

        lblNyAdress.setText("Ny Adress");

        btnNyAdress.setText("Ändra");
        btnNyAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyAdressActionPerformed(evt);
            }
        });

        btnEpost.setText("Ändra");
        btnEpost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEpostActionPerformed(evt);
            }
        });

        btnLosenord.setText("Ändra");
        btnLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLosenordActionPerformed(evt);
            }
        });

        btnTelefonNummer.setText("Ändra");
        btnTelefonNummer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelefonNummerActionPerformed(evt);
            }
        });

        btnAdress.setText("Ändra");
        btnAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdressActionPerformed(evt);
            }
        });

        lblAtEpost.setText("@example.com");

        lblAtNyEpost.setText("@example.com");

        lblFelmeddelande.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFelmeddelande.setForeground(new java.awt.Color(255, 0, 0));

        lblNyAdressNr.setText("Nummer:");

        lblNyAdressGata.setText("Gata:");

        lblNyAdressStad.setText("Stad:");

        btnNyAdressAvbryt.setText("Avbryt");
        btnNyAdressAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyAdressAvbrytActionPerformed(evt);
            }
        });

        btnNyttTelefonNummerAvbryt.setText("Avbryt");
        btnNyttTelefonNummerAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyttTelefonNummerAvbrytActionPerformed(evt);
            }
        });

        btnNyttLosenordAvbryt.setText("Avbryt");
        btnNyttLosenordAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyttLosenordAvbrytActionPerformed(evt);
            }
        });

        btnNyEpostAvbryt.setText("Avbryt");
        btnNyEpostAvbryt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyEpostAvbrytActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblEpost)
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnNyttLosenord))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfEpost, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(tfNyEpost))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAtNyEpost)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNyEpost))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAtEpost)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEpost))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNyttLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLosenord))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdress)
                                    .addComponent(lblNyttTelefonNummer)
                                    .addComponent(lblNyAdress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfNyttTelefonNummer, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(tfTelefonNummer)
                                            .addComponent(tfAdress)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblNyAdressNr)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblNyAdressGata)))
                                        .addGap(45, 45, 45)
                                        .addComponent(lblNyAdressStad)
                                        .addGap(152, 152, 152))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(tfNyAdressNr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNyAdressGata, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNyAdressStad, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblFelmeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTelefonNummer, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNyttTelefonNummer, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNyAdress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAdress, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRubrik)
                            .addComponent(lblNyEpost)
                            .addComponent(lblLosenord)
                            .addComponent(lblNyttLosenord)
                            .addComponent(lblTelefonNummer))
                        .addGap(519, 519, 519)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNyAdressAvbryt)
                    .addComponent(btnNyttTelefonNummerAvbryt)
                    .addComponent(btnNyttLosenordAvbryt)
                    .addComponent(btnNyEpostAvbryt)
                    .addComponent(btnTillbaka))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEpost)
                    .addComponent(lblAtEpost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNyEpost)
                    .addComponent(tfNyEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNyEpost)
                    .addComponent(lblAtNyEpost)
                    .addComponent(btnNyEpostAvbryt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(tfLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNyttLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNyttLosenord)
                    .addComponent(btnNyttLosenord)
                    .addComponent(btnNyttLosenordAvbryt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonNummer)
                    .addComponent(tfTelefonNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTelefonNummer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNyttTelefonNummer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNyttTelefonNummer)
                    .addComponent(lblNyttTelefonNummer)
                    .addComponent(btnNyttTelefonNummerAvbryt))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdress)
                            .addComponent(btnAdress))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNyAdressNr)
                            .addComponent(lblNyAdressGata)
                            .addComponent(lblNyAdressStad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNyAdressNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNyAdressGata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNyAdressStad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNyAdress)
                            .addComponent(btnNyAdress)
                            .addComponent(btnNyAdressAvbryt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblFelmeddelande, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbaka)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEpostActionPerformed
        
        setSynlighet("alla", false);
        setSynlighet("epost", true);
        
    }//GEN-LAST:event_btnEpostActionPerformed

    private void btnLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLosenordActionPerformed
        
        setSynlighet("alla", false);
        setSynlighet("losenord", true);
        
    }//GEN-LAST:event_btnLosenordActionPerformed

    private void btnTelefonNummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelefonNummerActionPerformed
        
        setSynlighet("alla", false);
        setSynlighet("telefonNummer", true);
        
    }//GEN-LAST:event_btnTelefonNummerActionPerformed

    private void btnAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdressActionPerformed
        
        setSynlighet("alla", false);
        setSynlighet("adress", true);
        
    }//GEN-LAST:event_btnAdressActionPerformed

    private void btnNyEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyEpostActionPerformed
        
        String nyEpost = tfNyEpost.getText();
        konto.setEpost(nyEpost);
        tfEpost.setText(nyEpost);
        setSynlighet("epost", false);
        
    }//GEN-LAST:event_btnNyEpostActionPerformed

    private void btnNyttLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyttLosenordActionPerformed
        
        String nyttLosenord = tfNyttLosenord.getText();
        konto.setLosenord(nyttLosenord);
        tfLosenord.setText(nyttLosenord);
        setSynlighet("losenord", false);
        
    }//GEN-LAST:event_btnNyttLosenordActionPerformed

    private void btnNyttTelefonNummerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyttTelefonNummerActionPerformed
        
        String nyttTelefonNummer = tfNyttTelefonNummer.getText();
        konto.setTelefonNummer(nyttTelefonNummer);
        tfTelefonNummer.setText(nyttTelefonNummer);
        setSynlighet("TelefonNummer", false);
        
    }//GEN-LAST:event_btnNyttTelefonNummerActionPerformed

    private void btnNyAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyAdressActionPerformed
        
        String nyAdressNr = tfNyAdressNr.getText();
        String nyAdressGata = tfNyAdressGata.getText();
        String nyAdressStad = tfNyAdressStad.getText();
        String nyAdress = nyAdressNr + " " + nyAdressGata + ", " + nyAdressStad;
        System.out.println(nyAdress);
         
        
            konto.setAdress(nyAdress);
            setSynlighet("adress", false);
            tfAdress.setText(nyAdress);
        
        
       
    }//GEN-LAST:event_btnNyAdressActionPerformed

    private void btnNyEpostAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyEpostAvbrytActionPerformed
        
        tfNyEpost.setText("");
        setSynlighet("epost", false);
        
    }//GEN-LAST:event_btnNyEpostAvbrytActionPerformed

    private void btnNyttLosenordAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyttLosenordAvbrytActionPerformed
        
        tfNyttLosenord.setText("");
        setSynlighet("losenord", false);
        
    }//GEN-LAST:event_btnNyttLosenordAvbrytActionPerformed

    private void btnNyttTelefonNummerAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyttTelefonNummerAvbrytActionPerformed
        
        tfNyttTelefonNummer.setText("");
        setSynlighet("telefonNummer", false);
        
    }//GEN-LAST:event_btnNyttTelefonNummerAvbrytActionPerformed

    private void btnNyAdressAvbrytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyAdressAvbrytActionPerformed
        
        tfNyAdressNr.setText("");
        tfNyAdressGata.setText("");
        tfNyAdressStad.setText("");
        setSynlighet("adress", false);
        
    }//GEN-LAST:event_btnNyAdressAvbrytActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        Meny meny = new Meny(idb, anstalldID, "");
        meny.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kontoinstallningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kontoinstallningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kontoinstallningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kontoinstallningar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Kontoinstallningar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdress;
    private javax.swing.JButton btnEpost;
    private javax.swing.JButton btnLosenord;
    private javax.swing.JButton btnNyAdress;
    private javax.swing.JButton btnNyAdressAvbryt;
    private javax.swing.JButton btnNyEpost;
    private javax.swing.JButton btnNyEpostAvbryt;
    private javax.swing.JButton btnNyttLosenord;
    private javax.swing.JButton btnNyttLosenordAvbryt;
    private javax.swing.JButton btnNyttTelefonNummer;
    private javax.swing.JButton btnNyttTelefonNummerAvbryt;
    private javax.swing.JButton btnTelefonNummer;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblAtEpost;
    private javax.swing.JLabel lblAtNyEpost;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblNyAdress;
    private javax.swing.JLabel lblNyAdressGata;
    private javax.swing.JLabel lblNyAdressNr;
    private javax.swing.JLabel lblNyAdressStad;
    private javax.swing.JLabel lblNyEpost;
    private javax.swing.JLabel lblNyttLosenord;
    private javax.swing.JLabel lblNyttTelefonNummer;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblTelefonNummer;
    private javax.swing.JTextField tfAdress;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JTextField tfLosenord;
    private javax.swing.JTextField tfNyAdressGata;
    private javax.swing.JTextField tfNyAdressNr;
    private javax.swing.JTextField tfNyAdressStad;
    private javax.swing.JTextField tfNyEpost;
    private javax.swing.JTextField tfNyttLosenord;
    private javax.swing.JTextField tfNyttTelefonNummer;
    private javax.swing.JTextField tfTelefonNummer;
    // End of variables declaration//GEN-END:variables
}
