/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author natha, Israael, JillWithJ
 */
public class LandMeny extends javax.swing.JFrame {
    private String anstalldID;
    private InfDB idb;
    private Projekt projekt;
    private Land land;

    
    public LandMeny(InfDB idb, String anstalldID){
        this.anstalldID = anstalldID;
        this.idb = idb;
        projekt = new Projekt(idb, anstalldID);
        land = new Land(idb, anstalldID);
        initComponents();
        setSynlighet(false);
        lblFelmeddelande.setVisible(false);
        
    }

    private void addLand(){
        
        int lid = Integer.parseInt(tfAddLid.getText());
        String namn = tfAddNamn.getText();
        String sprak = tfAddSprak.getText();
        String valutaString = tfValuta.getText();
        
        double valuta = Double.parseDouble(valutaString);
        String tidszon = tfAddTidszon.getText();
        String politiskStruktur = tfAddPolitiskStruktur.getText();
        String ekonomi = tfEkonomi.getText();
      
        
        land.addLand(lid, namn, sprak, valuta, tidszon, politiskStruktur, ekonomi);
     
    }
    
    private void changeLand(){
        try {
        int lid = Integer.parseInt(tfAddLid.getText());
        String namn = tfAddNamn.getText();
        String sprak = tfAddSprak.getText();
        String  valutaString = tfValuta.getText();
   
        double valuta = Double.parseDouble(valutaString);
        String tidszon = tfAddTidszon.getText();
        String politiskStruktur = tfAddPolitiskStruktur.getText();
        String ekonomi = tfEkonomi.getText();
        
        
        land.changeLand(lid,namn, sprak, valuta, tidszon, politiskStruktur, ekonomi);
        lblFelmeddelande.setText("Landet är ändrat");
        } catch (NumberFormatException e){
            lblFelmeddelande.setText("Fel. Valutan måste vara av numeriskt värde");
        }catch (Exception e){
            lblFelmeddelande.setText("Ett fel inträffade: " + e.getMessage());
        }
        lblFelmeddelande.setVisible(true);
    }
    
    private void setSynlighet(boolean synlighet){
        
        lblAddLid.setVisible(synlighet);
        lblAddNamn.setVisible(synlighet);
        lblAddSprak.setVisible(synlighet);
        lblAddValuta.setVisible(synlighet);
        lblEkonomi.setVisible(synlighet);
        lblPolitiskStruktur.setVisible(synlighet);
        lblTidzon.setVisible(synlighet);
        lblRubrik.setVisible(synlighet);
        
        tfAddLid.setVisible(synlighet);
        tfAddNamn.setVisible(synlighet);
        tfAddPolitiskStruktur.setVisible(synlighet);
        tfAddSprak.setVisible(synlighet);
        tfAddTidszon.setVisible(synlighet);
        tfEkonomi.setVisible(synlighet);
        tfValuta.setVisible(synlighet);
        
        btnAction.setVisible(synlighet);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfAddNamn = new javax.swing.JTextField();
        tfAddSprak = new javax.swing.JTextField();
        tfValuta = new javax.swing.JTextField();
        tfAddTidszon = new javax.swing.JTextField();
        tfAddPolitiskStruktur = new javax.swing.JTextField();
        tfEkonomi = new javax.swing.JTextField();
        lblAddNamn = new javax.swing.JLabel();
        lblAddSprak = new javax.swing.JLabel();
        lblAddValuta = new javax.swing.JLabel();
        lblTidzon = new javax.swing.JLabel();
        lblPolitiskStruktur = new javax.swing.JLabel();
        lblEkonomi = new javax.swing.JLabel();
        btnAddLand = new javax.swing.JButton();
        btnChangeLand = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        btnAction = new javax.swing.JButton();
        lblRubrik = new javax.swing.JLabel();
        lblFelmeddelande = new javax.swing.JLabel();
        lblAddLid = new javax.swing.JLabel();
        tfAddLid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAddNamn.setText("Namn");

        lblAddSprak.setText("Språk");

        lblAddValuta.setText("Valuta");

        lblTidzon.setText("Tidszon");

        lblPolitiskStruktur.setText("Politisk Struktur");

        lblEkonomi.setText("Ekonomi");

        btnAddLand.setText("Lägg till Land");
        btnAddLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLandActionPerformed(evt);
            }
        });

        btnChangeLand.setText("Ändra Land");
        btnChangeLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeLandActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnAction.setText("Gör");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });

        lblRubrik.setText("Rubrik");

        lblFelmeddelande.setText("Felmeddelande");

        lblAddLid.setText("Land-ID");

        tfAddLid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddLidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnAddLand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChangeLand)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTillbaka)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFelmeddelande)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAddSprak, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAddValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTidzon, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblRubrik)
                                                    .addComponent(lblAddNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addComponent(lblPolitiskStruktur)
                                    .addComponent(lblEkonomi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfAddSprak, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAddTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAddPolitiskStruktur, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfAddNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAction))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfAddLid, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfEkonomi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblAddLid, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddLand)
                    .addComponent(btnChangeLand))
                .addGap(81, 81, 81)
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddNamn)
                    .addComponent(btnAction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddSprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddSprak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddValuta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTidzon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAddPolitiskStruktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolitiskStruktur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEkonomi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddLid)
                    .addComponent(tfAddLid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lblFelmeddelande)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbaka)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLandActionPerformed
     
        lblRubrik.setText("Lägg Till Land");
        btnAction.setText("Lägg Till");
        setSynlighet(true);
        
    }//GEN-LAST:event_btnAddLandActionPerformed

    private void btnChangeLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeLandActionPerformed
        
        lblRubrik.setText("Ändra Land");
        btnAction.setText("Ändra");
        setSynlighet(true); 
        
    }//GEN-LAST:event_btnChangeLandActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        Meny meny = new Meny(idb, anstalldID, "");
        meny.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        
        String knapp = btnAction.getText();
        try{
        if(knapp.equals("Lägg Till")){
            addLand();
            lblFelmeddelande.setText("Nytt land tillagt");
        }else if (knapp.equals("Ändra")){
            changeLand();
            lblFelmeddelande.setText("Landet är ändrat");
        }
        } catch (NumberFormatException e){
            lblFelmeddelande.setText("Fel. Valutan måste vara av numeriskt värde");
        }catch (Exception e) {
            lblFelmeddelande.setText("ett fel inträffade: " + e.getMessage());
        }
            lblFelmeddelande.setVisible(true);
        
    }//GEN-LAST:event_btnActionActionPerformed

    private void tfAddLidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddLidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddLidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LandMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnAddLand;
    private javax.swing.JButton btnChangeLand;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JLabel lblAddLid;
    private javax.swing.JLabel lblAddNamn;
    private javax.swing.JLabel lblAddSprak;
    private javax.swing.JLabel lblAddValuta;
    private javax.swing.JLabel lblEkonomi;
    private javax.swing.JLabel lblFelmeddelande;
    private javax.swing.JLabel lblPolitiskStruktur;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblTidzon;
    private javax.swing.JTextField tfAddLid;
    private javax.swing.JTextField tfAddNamn;
    private javax.swing.JTextField tfAddPolitiskStruktur;
    private javax.swing.JTextField tfAddSprak;
    private javax.swing.JTextField tfAddTidszon;
    private javax.swing.JTextField tfEkonomi;
    private javax.swing.JTextField tfValuta;
    // End of variables declaration//GEN-END:variables
}
