/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author natha
 */
public class LandMeny extends javax.swing.JFrame {
    private String anstalldID;
    private InfDB idb;
    private Projekt projekt;

    /**
     * Creates new form LandMeny
     */
    public LandMeny(InfDB idb, String anstalldID){
        this.anstalldID = anstalldID;
        this.idb = idb;
        projekt = new Projekt(idb, anstalldID);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblAddLand = new javax.swing.JLabel();
        tfAddNamn = new javax.swing.JTextField();
        tfAddSprak = new javax.swing.JTextField();
        tfValuta = new javax.swing.JTextField();
        tfAddTidszon = new javax.swing.JTextField();
        tfAddPolitiskStruktur = new javax.swing.JTextField();
        tfEkonomi = new javax.swing.JTextField();
        lblAddNamn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblAddSprak = new javax.swing.JLabel();
        lblAddValuta = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAddNamn = new javax.swing.JButton();
        btnChangeLand = new javax.swing.JButton();
        lblChangeLand = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAddLand.setText("Lägg till land");

        tfAddNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddNamnActionPerformed(evt);
            }
        });

        tfAddTidszon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddTidszonActionPerformed(evt);
            }
        });

        lblAddNamn.setText("Namn");

        lblAddSprak.setText("Språk");

        lblAddValuta.setText("Valuta");

        jLabel2.setText("Tidszon");

        jLabel3.setText("Politisk Struktur");

        jLabel4.setText("Ekonomi");

        btnAddNamn.setText("Lägg till Land");
        btnAddNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNamnActionPerformed(evt);
            }
        });

        btnChangeLand.setText("Ändra Land");
        btnChangeLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeLandActionPerformed(evt);
            }
        });

        lblChangeLand.setText("Ändra land");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfAddSprak, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAddNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAddNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(139, 139, 139)
                                .addComponent(btnAddNamn)
                                .addGap(123, 123, 123)
                                .addComponent(btnChangeLand))
                            .addComponent(lblAddValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfValuta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAddPolitiskStruktur, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAddSprak, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(tfAddTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblAddLand)
                        .addGap(324, 324, 324)
                        .addComponent(lblChangeLand, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddLand, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChangeLand))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblAddNamn)
                        .addGap(18, 18, 18)
                        .addComponent(tfAddNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChangeLand)
                            .addComponent(btnAddNamn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAddSprak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfAddSprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblAddValuta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfValuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAddTidszon, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAddPolitiskStruktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEkonomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfAddNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddNamnActionPerformed

    private void tfAddTidszonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddTidszonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddTidszonActionPerformed

    private void btnAddNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNamnActionPerformed
     String namn = tfAddNamn.getText();
     String sprak = tfAddSprak.getText();
     String valutaString = tfValuta.getText();
     int valutaInt = Integer.parseInt(valutaString);
     double valuta = valutaInt;
     String tidszon = tfAddTidszon.getText();
     String politiskStruktur = tfAddPolitiskStruktur.getText();
     String ekonomi = tfEkonomi.getText();
     String lid = projekt.getLandID(namn);
     projekt.addLand(lid, namn, sprak, Double.NaN, tidszon, politiskStruktur, ekonomi);
    }//GEN-LAST:event_btnAddNamnActionPerformed

    private void btnChangeLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeLandActionPerformed
        String namn = tfAddNamn.getText();
        String sprak = tfAddSprak.getText();
        String  valutaString = tfValuta.getText();
        int valutaInt = Integer.parseInt(valutaString);
        double valuta = valutaInt;
        String tidszon = tfAddTidszon.getText();
        String politiskStruktur = tfAddPolitiskStruktur.getText();
        String ekonomi = tfEkonomi.getText();
        String lid = projekt.getLandID(namn);
        projekt.changeLand(lid,namn, sprak, valuta, tidszon, politiskStruktur, ekonomi);
                
                
    }//GEN-LAST:event_btnChangeLandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LandMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNamn;
    private javax.swing.JButton btnChangeLand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAddLand;
    private javax.swing.JLabel lblAddNamn;
    private javax.swing.JLabel lblAddSprak;
    private javax.swing.JLabel lblAddValuta;
    private javax.swing.JLabel lblChangeLand;
    private javax.swing.JTextField tfAddNamn;
    private javax.swing.JTextField tfAddPolitiskStruktur;
    private javax.swing.JTextField tfAddSprak;
    private javax.swing.JTextField tfAddTidszon;
    private javax.swing.JTextField tfEkonomi;
    private javax.swing.JTextField tfValuta;
    // End of variables declaration//GEN-END:variables
}
