/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2024;

import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author JillWithJ, Israael, Natha
 */
public class Meny extends javax.swing.JFrame {

    private InfDB idb;
    private String inloggadAnv;
    private String anstalldID;
    private String namn;
    private Validering validering;
    private Anstallning anstallning;
    
    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb, String inloggadAnv) {
        this.idb = idb;
        this.inloggadAnv = inloggadAnv;
        
        
        
        anstalldID = "1";
        //anstalldID = "6";
        //anstalldID = anstallning.getInloggadAID(inloggadAnv);
        validering = new Validering(idb, anstalldID);
        anstallning = new Anstallning(idb, inloggadAnv);
        
        String atkomst = anstallning.getAtkomst(anstalldID);
        namn = anstallning.getNamn(anstalldID);
        
        
        initComponents();
        lblInloggad.setText("Välkommen " + atkomst + " " + namn);
        setAdminBtns();
    }
    public Meny(InfDB idb, String aid, String inget) {
        this.idb = idb;
        //anstalldID = aid;
        
        
        
        anstalldID = "1";
        //aid = "6";
        validering = new Validering(idb, anstalldID);
        anstallning = new Anstallning(idb, anstalldID, "");
        
        String atkomst = anstallning.getAtkomst(anstalldID);
        namn = anstallning.getNamn(anstalldID);
        
        
        initComponents();
        lblInloggad.setText("Välkommen " + atkomst + " " + namn);
        setAdminBtns();
    }
    
    private void setAdminBtns(){
        
        boolean admin = anstallning.getAdmin(anstalldID);

        if(admin)
        {    
            btnLand.setVisible(true);
            btnPartners.setVisible(true);
        }else{
            btnLand.setVisible(false);
            btnPartners.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInloggad = new javax.swing.JLabel();
        btnKonto = new javax.swing.JButton();
        btnAnstallda = new javax.swing.JButton();
        btnAvdelning = new javax.swing.JButton();
        btnProjekt = new javax.swing.JButton();
        btnLand = new javax.swing.JButton();
        btnPartners = new javax.swing.JButton();
        btnHallbarhetsmal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInloggad.setText("jLabel1");

        btnKonto.setText("Mitt Konto");
        btnKonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKontoActionPerformed(evt);
            }
        });

        btnAnstallda.setText("Anställda");
        btnAnstallda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnstalldaActionPerformed(evt);
            }
        });

        btnAvdelning.setText("Avdelning");
        btnAvdelning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvdelningActionPerformed(evt);
            }
        });

        btnProjekt.setText("Projekt");
        btnProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProjektActionPerformed(evt);
            }
        });

        btnLand.setText("Land");
        btnLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLandActionPerformed(evt);
            }
        });

        btnPartners.setText("Partners");
        btnPartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPartnersActionPerformed(evt);
            }
        });

        btnHallbarhetsmal.setText("Hållbarhetsmål");
        btnHallbarhetsmal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHallbarhetsmalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInloggad)
                    .addComponent(btnPartners)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKonto)
                            .addComponent(btnAnstallda)
                            .addComponent(btnProjekt))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLand)
                            .addComponent(btnAvdelning)
                            .addComponent(btnHallbarhetsmal))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInloggad)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnHallbarhetsmal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKonto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnstallda)
                    .addComponent(btnAvdelning))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProjekt)
                    .addComponent(btnLand))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPartners)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKontoActionPerformed
        
        Kontoinstallningar mittKonto = new Kontoinstallningar(idb, anstalldID);
        mittKonto.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnKontoActionPerformed

    private void btnAnstalldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnstalldaActionPerformed
        
        RedigeraAnstallda redigeraAnstallda = new RedigeraAnstallda(idb, anstalldID);
        redigeraAnstallda.setVisible(true);
        
    }//GEN-LAST:event_btnAnstalldaActionPerformed

    private void btnAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvdelningActionPerformed
        
        AvdelningMeny avdelningM = new AvdelningMeny(idb, anstalldID);
        avdelningM.setVisible(true);
        
    }//GEN-LAST:event_btnAvdelningActionPerformed

    private void btnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektActionPerformed
        
        ProjektMeny projektMeny = new ProjektMeny(idb, anstalldID);
        projektMeny.setVisible(true);
        
    }//GEN-LAST:event_btnProjektActionPerformed

    private void btnLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandActionPerformed
        
        LandMeny landMeny = new LandMeny(idb, anstalldID);
        landMeny.setVisible(true);
        
    }//GEN-LAST:event_btnLandActionPerformed

    private void btnPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnersActionPerformed
        
        PartnersMeny partnersMeny = new PartnersMeny(idb, anstalldID);
        partnersMeny.setVisible(true);
        
    }//GEN-LAST:event_btnPartnersActionPerformed

    private void btnHallbarhetsmalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHallbarhetsmalActionPerformed
        
        HallbarhetsmalMeny hallbarhetsmalMeny = new HallbarhetsmalMeny(idb, anstalldID);
        hallbarhetsmalMeny.setVisible(true);
        
    }//GEN-LAST:event_btnHallbarhetsmalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Meny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnstallda;
    private javax.swing.JButton btnAvdelning;
    private javax.swing.JButton btnHallbarhetsmal;
    private javax.swing.JButton btnKonto;
    private javax.swing.JButton btnLand;
    private javax.swing.JButton btnPartners;
    private javax.swing.JButton btnProjekt;
    private javax.swing.JLabel lblInloggad;
    // End of variables declaration//GEN-END:variables
}
